"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),crypto=require("node:crypto").webcrypto;
const base=Date.parse("2026-10-09T03:30:00Z"),modelSource=fs.readFileSync(process.argv[2],"utf8"),uiSource=fs.readFileSync(process.argv[3],"utf8");
function setup(withModel=true){
  class Element{constructor(){this.value="";this.checked=false;this.disabled=false;this.textContent="";this.children=[];this.files=[];this.options=[];this.selectedIndex=0;}append(e){this.children.push(e);}replaceChildren(){this.children=[];}remove(){}click(){this.clicked=true;}}
  const nodes={},get=id=>nodes[id]||(nodes[id]=new Element()),downloads=[],listeners={};let clock=base;
  class Clock extends Date{static now(){return clock;}}
  const window={addEventListener:(kind,fn)=>listeners[kind]=fn},document={getElementById:get,createElement:()=>new Element(),body:new Element()};
  const context=vm.createContext({window,document,Date:Clock,Intl,Blob,TextEncoder,Uint8Array,crypto,
    URL:{createObjectURL:b=>{downloads.push(b);return "blob:private-synthetic";},revokeObjectURL:()=>{}},setTimeout:fn=>fn(),
    fetch:()=>{throw Error("unexpected_network");},localStorage:{setItem:()=>{throw Error("unexpected_storage");}}});
  get("store").value="900001";get("store").options=[{textContent:"合成门店一"}];
  get("experience-queue").value="ordinary";get("experience-table").value="unknown";get("experience-kind").value="checked_in";
  get("experience-lower").value="2026-10-09T11:00";get("experience-upper").value="2026-10-09T11:05";
  if(withModel){vm.runInContext(modelSource,context);window.SushiWaitExperience=context.SushiWaitExperience;}
  vm.runInContext(uiSource,context);
  return {get,downloads,listeners,window,clock:n=>clock=n,begin:()=>get("experience-start").onclick(),
    clear:()=>get("experience-clear").onclick(),download:()=>get("experience-download").onclick()};
}
let cases=0;async function check(name,fn){await fn();cases++;}
async function blobValue(ui){ui.download();return JSON.parse(await ui.downloads.at(-1).text());}
(async()=>{
  await check("requires human confirmation and an explicit issued interval",()=>{const ui=setup();ui.begin();assert.equal(ui.get("experience-events").children.length,0);ui.get("experience-confirm").checked=true;ui.begin();assert.equal(ui.get("experience-events").children.length,1);assert(ui.get("experience-start").disabled);assert(ui.get("experience-party").disabled);});
  await check("scope stays with the original store and only human actions add events",async()=>{const ui=setup();ui.get("experience-confirm").checked=true;ui.begin();ui.get("store").value="900002";ui.clock(base+60000);assert.equal(ui.get("experience-events").children.length,1);ui.get("experience-kind").value="called";ui.get("experience-now").onclick();const value=await blobValue(ui),r=value.revisions.at(-1);assert.equal(r.store_id,"900001");assert.equal(r.party_size,null);assert.equal(r.table_type,"unknown");assert.equal(r.events[1].event_time_lower,"2026-10-09T03:31:00.000Z");assert(!JSON.stringify(value).includes("ticket_number"));assert(!JSON.stringify(value).includes("received_at"));assert(ui.get("experience-scope").textContent.includes("合成门店一"));});
  await check("requested download is not persistence acknowledgement",async()=>{const ui=setup();ui.get("experience-confirm").checked=true;ui.begin();ui.clear();assert.equal(ui.get("experience-events").children.length,1);ui.download();ui.clear();assert.equal(ui.get("experience-events").children.length,1);let prevented=false;ui.listeners.beforeunload({preventDefault:()=>prevented=true});assert(prevented);ui.get("experience-saved").checked=true;prevented=false;ui.listeners.beforeunload({preventDefault:()=>prevented=true});assert(!prevented);ui.clear();assert.equal(ui.get("experience-events").children.length,0);assert.equal(ui.get("experience-queue").value,"unknown");assert.equal(ui.get("experience-party").value,"");});
  await check("new revisions invalidate the prior saved acknowledgement",()=>{const ui=setup();ui.get("experience-confirm").checked=true;ui.begin();ui.download();ui.get("experience-saved").checked=true;ui.get("experience-now").onclick();assert(!ui.get("experience-saved").checked);ui.clear();assert.equal(ui.get("experience-events").children.length,2);});
  await check("local import restores all private revisions without any upload",async()=>{const source=setup();source.get("experience-confirm").checked=true;source.begin();source.get("experience-kind").value="called";source.get("experience-now").onclick();const body=JSON.stringify(await blobValue(source)),ui=setup();ui.get("experience-import").files=[{size:body.length,text:async()=>body}];await ui.get("experience-import").onchange();assert.equal(ui.get("experience-events").children.length,2);assert(ui.get("experience-start").disabled);assert(!ui.get("experience-saved").checked);assert.deepEqual(await blobValue(ui),JSON.parse(body));});
  await check("active drafts and oversized or malformed imports stay intact",async()=>{const ui=setup();ui.get("experience-confirm").checked=true;ui.begin();let read=false;ui.get("experience-import").files=[{size:1,text:async()=>{read=true;return "{}";}}];await ui.get("experience-import").onchange();assert(!read);assert.equal(ui.get("experience-events").children.length,1);const empty=setup();for(const file of [{size:16385,text:async()=>{throw Error("read too large");}},{size:1,text:async()=>"{"}]){empty.get("experience-import").files=[file];await empty.get("experience-import").onchange();assert.equal(empty.get("experience-events").children.length,0);assert(!empty.get("experience-start").disabled);}});
  await check("an import finishing late cannot overwrite a newly begun draft",async()=>{const source=setup();source.get("experience-confirm").checked=true;source.begin();const body=JSON.stringify(await blobValue(source)),ui=setup();let finish;ui.get("experience-import").files=[{size:body.length,text:()=>new Promise(resolve=>finish=resolve)}];const pending=ui.get("experience-import").onchange();ui.get("store").value="900002";ui.get("experience-confirm").checked=true;ui.begin();finish(body);await pending;const value=await blobValue(ui);assert.equal(value.revisions[0].store_id,"900002");assert.notEqual(value.revisions[0].episode_id,JSON.parse(body).revisions[0].episode_id);});
  await check("terminal observation ends the draft without inventing a call",async()=>{const ui=setup();ui.get("experience-confirm").checked=true;ui.begin();ui.get("experience-kind").value="observation_ended";ui.get("experience-now").onclick();assert(ui.get("experience-add").disabled);assert(ui.get("experience-now").disabled);const value=await blobValue(ui);assert.deepEqual(value.revisions.at(-1).events.map(e=>e.event_type),["issued","observation_ended"]);});
  await check("missing model disables record controls",()=>{const ui=setup(false);assert(ui.get("experience-start").disabled);assert(ui.get("experience-download").disabled);assert.equal(ui.get("experience-events").children.length,0);});
  console.log(`${cases} experience-ui cases passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
