"use strict";
const assert=require("node:assert/strict");Object.defineProperty(globalThis,"crypto",{value:require("node:crypto").webcrypto,configurable:true});
const model=require(process.argv[2]),base=Date.parse("2026-10-09T03:30:00Z"),iso=ms=>new Date(ms).toISOString();
function first(changes={}){return model.begin({storeId:"900001",queueType:"ordinary",partySize:null,tableType:"unknown",dataOrigin:"synthetic",lower:iso(base-30*60000),upper:iso(base-25*60000),now:base,...changes});}
function call(bundle=first(),changes={}){return model.append(bundle,{kind:"called",lower:iso(base+60000),upper:iso(base+120000),now:base+180000,...changes});}
if(process.argv.includes("--fixture")){let bundle=call();bundle=model.append(bundle,{kind:"seated",lower:iso(base+240000),upper:iso(base+300000),now:base+360000});console.log(model.exportBundle(bundle,base+360000));process.exit(0);}
let cases=0;function check(name,fn){fn();cases++;}
check("explicit issued interval, unknown fields and no ticket number",()=>{const r=first({number:"PrivateTicket98765"}),e=r.revisions[0];assert.equal(e.party_size,null);assert.equal(e.table_type,"unknown");assert.equal(e.events[0].event_time_lower,iso(base-30*60000));assert.equal(e.events[0].verification_status,"unverified");assert(!JSON.stringify(r).includes("PrivateTicket98765"));});
check("successive revisions preserve identifiers and earlier timestamps",()=>{const r=first(),before=JSON.stringify(r),next=call(r);assert.equal(JSON.stringify(r),before);assert.equal(next.revisions.length,2);assert.deepEqual(next.revisions[1].events[0],r.revisions[0].events[0]);assert.equal(next.revisions[1].supersedes_revision,1);});
check("terminal observation does not manufacture a call",()=>{const r=model.append(first(),{kind:"observation_ended",lower:iso(base),upper:iso(base),now:base});assert.deepEqual(r.revisions.at(-1).events.map(e=>e.event_type),["issued","observation_ended"]);assert.throws(()=>call(r));});
check("duplicate, future and reversed events rejected without mutation",()=>{const r=call(),before=JSON.stringify(r);assert.throws(()=>call(r));assert.throws(()=>call(first(),{upper:iso(base+180001)}));assert.throws(()=>call(first(),{lower:iso(base-40*60000),upper:iso(base-35*60000)}));assert.equal(JSON.stringify(r),before);});
for(const changes of [{storeId:"0"},{storeId:"01"},{storeId:"2147483648"},{queueType:"aggregate"},{partySize:true},{partySize:1.5},{partySize:0},{tableType:"all"},{dataOrigin:"official"},{lower:iso(base+1),upper:iso(base+1)}])check("scope and time rejection",()=>assert.throws(()=>first(changes)));
check("full-chain export remains independently self-reported",()=>{const r=call(first({dataOrigin:"self_reported"})),text=model.exportBundle(r,base+180000);assert.equal(JSON.parse(text).revisions[1].data_origin,"self_reported");assert(!text.includes('"received_at"'));assert(!text.includes('"training_eligible"'));assert(new TextEncoder().encode(text).length<16384);});
check("object property order is not a revision change",()=>{const r=call();r.revisions[1].events[0]=Object.fromEntries(Object.entries(r.revisions[1].events[0]).reverse());assert(model.validateBundle(r,base+180000));});
for(const mutate of [r=>r.revisions.shift(),r=>r.revisions[1].events[0].event_time_lower=iso(base-29*60000),r=>r.revisions[1].party_size=2,r=>r.revisions[1].events[1].verification_status="verified",r=>r.private_identity="Private",r=>r.exported_at=iso(base+180001)])check("modified or incomplete bundle rejected",()=>{const r=call();mutate(r);assert.throws(()=>model.validateBundle(r,base+180000));});
check("local minute precision is preserved as a bounded interval",()=>{assert.deepEqual(model.localInterval("2026-10-09T11:00","2026-10-09T11:05",base),{lower:iso(base-30*60000),upper:iso(base-25*60000+59999)});assert.deepEqual(model.localInterval("2026-10-09T11:30","2026-10-09T11:30",base+120),{lower:iso(base),upper:iso(base+120)});});
check("invalid calendar, partial range and future local input rejected",()=>{for(const pair of [["2026-02-30T11:00","2026-02-30T11:01"],["2026-10-09T11:31","2026-10-09T11:31"],["2026-10-09T11:00",""],["2026-10-09T11:20","2026-10-09T11:05"]])assert.throws(()=>model.localInterval(...pair,base));});
check("no weak UUID fallback",()=>{const saved=globalThis.crypto;Object.defineProperty(globalThis,"crypto",{value:null,configurable:true});assert.throws(()=>first(),/secure_random_unavailable/);Object.defineProperty(globalThis,"crypto",{value:saved,configurable:true});});
console.log(`${cases} experience-model cases passed`);
