"use strict";
const $=id=>document.getElementById(id), dateFormat=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}), timeFormat=new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});
function today(){const parts=dateFormat.formatToParts(new Date()),v={};parts.forEach(p=>v[p.type]=p.value);return `${v.year}-${v.month}-${v.day}`;}
let index={days:{},store_names:{}},day=today(),detail=null,busy=false,detailRequestId=0;
async function get(path){const r=await fetch(path,{cache:"no-store",signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error("读取失败");return r.json();}
function textRow(values,parent){const tr=document.createElement("tr");values.forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.append(td);});parent.append(tr);return tr;}
function time(v){return v?timeFormat.format(new Date(v)):"—";}
function summaries(d){const all=index.days[d]||{},store=$("store").value;return store?(all[store]?[all[store]]:[]):Object.values(all);}
function coverage(items){const expected=items.reduce((n,s)=>n+s.expected_background_slots_so_far,0),seen=items.reduce((n,s)=>n+s.observed_background_slots,0);return expected?Math.min(1,seen/expected):null;}
function calendar(){const month=$("month").value;if(!/^\d{4}-\d{2}$/.test(month))return;const [year,m]=month.split("-").map(Number),n=new Date(Date.UTC(year,m,0)).getUTCDate(),start=(new Date(Date.UTC(year,m-1,1)).getUTCDay()+6)%7;$("calendar").replaceChildren();for(let i=0;i<start;i++)$("calendar").append(document.createElement("span"));for(let i=1;i<=n;i++){const d=`${month}-${String(i).padStart(2,"0")}`,items=summaries(d),c=coverage(items),b=document.createElement("button"),label=document.createElement("small");b.type="button";b.textContent=String(i);label.textContent=items.length?`${items.reduce((s,x)=>s+x.observations,0)} 组观测`:"无观测";b.append(label);if(items.length)b.classList.add(c!==null&&c>=.8&&(!$("store").value?items.length===Object.keys(index.store_names).length:true)?"covered":"partial");if(d===day)b.classList.add("selected");b.setAttribute("aria-label",`${d}，${label.textContent}`);b.onclick=()=>{day=d;calendar();showDay().catch(showError);};$("calendar").append(b);}}
function showError(){ $("status").textContent="统计服务暂时不可用；没有把读取失败当成零数据。"; }
async function showDay(){const requestId=++detailRequestId,selectedDay=day,store=$("store").value,items=summaries(day);$("date-title").textContent=`${day} · ${store?(index.store_names[store]||store):"全部门店"}`;$("rows").replaceChildren();items.forEach(s=>{const c=s.observed_slot_fraction_so_far,tr=textRow([index.store_names[s.store_id]||s.store_id,s.successful_pairs,`${s.failed_pairs} / ${s.scheduled_pause_slots}`,c===null?"—":`${(c*100).toFixed(1)}%`,time(s.last_observation_at)],$("rows"));tr.onclick=()=>{$("store").value=s.store_id;calendar();showDay().catch(showError);};});$("summary").textContent=items.length?`有观测的门店 ${items.length} 家，完整观测 ${items.reduce((n,s)=>n+s.successful_pairs,0)} 组。实际叫号总量和人流量仍未核实。`:"当天没有已保存的观测；不能据此判断门店没有客流。";$("detail").hidden=!store;detail=null;$("points").replaceChildren();["numbers","count","speed"].forEach(id=>plot(id,[]));$("graph-note").textContent="正在读取当天观测…";if(!store)return;const value=await get(`/api/v1/stores/${encodeURIComponent(store)}/days/${selectedDay}`);if(requestId!==detailRequestId||day!==selectedDay||$("store").value!==store)return;detail=value;graphs();}
function plot(id,points){const canvas=$(id),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(300,Math.round(rect.width*dpr));canvas.height=230*dpr;const c=canvas.getContext("2d");c.scale(dpr,dpr);const w=canvas.width/dpr,h=230;c.clearRect(0,0,w,h);c.strokeStyle="#d6dce1";c.beginPath();c.moveTo(60,12);c.lineTo(60,h-32);c.lineTo(w-12,h-32);c.stroke();c.fillStyle="#58636c";c.font="12px system-ui";if(!points.length){c.fillText("没有可绘制的有效观测",75,40);return;}const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),dx=Math.max(1,maxX-minX),dy=Math.max(1,maxY-minY);for(let i=0;i<4;i++){const y=minY+dy*i/3;c.fillText(Number(y.toFixed(2)).toString(),4,h-34-(h-50)*i/3);}c.fillText(time(minX),60,h-9);c.fillText(time(maxX),Math.max(60,w-80),h-9);points.forEach(([x,y,series])=>{c.fillStyle=["#3274a1","#bb7441","#638b4f"][series||0];c.beginPath();c.arc(60+(w-80)*(x-minX)/dx,h-34-(h-50)*(y-minY)/dy,2.4,0,Math.PI*2);c.fill();});}
function graphs(){if(!detail)return;const queue=$("queue").value,points=detail.points||[],numbers=[],counts=[],speed=[];points.forEach(p=>{(p.queues?.[queue]||[]).forEach((label,i)=>{if(/^\d+$/.test(label))numbers.push([Date.parse(p.queue_received_at),Number(label),i]);});if(p.count_raw!==null)counts.push([Date.parse(p.count_received_at),p.count_raw,0]);if(p.comparison_state==="comparable_display_sets"&&p.interval_seconds>0&&p.removed_labels)speed.push([Date.parse(p.queue_received_at),p.removed_labels[queue]*60/p.interval_seconds,0]);});plot("numbers",numbers);plot("count",counts);plot("speed",speed);$("points").replaceChildren();points.slice(-60).reverse().forEach(p=>textRow([time(p.queue_received_at),(p.queues?.[queue]||[]).join("、")||"未显示",p.count_raw===null?"未知":p.count_raw,p.scheduled_pause?"营业边界暂停":p.pair_ok?"已保存":"部分成功或失败"],$("points")));$("graph-note").textContent=`图表返回 ${points.length} 组。${detail.graph_truncated?"图表投影有截断，完整原始观测仍保存在数据库。":"当前图表投影未截断。"}`;}
async function refresh(){if(busy)return;busy=true;$("refresh").disabled=true;try{const selected=$("store").value;index=await get("/api/v1/days");$("store").replaceChildren();const all=document.createElement("option");all.value="";all.textContent="全部门店";$("store").append(all);Object.entries(index.store_names).forEach(([id,name])=>{const o=document.createElement("option");o.value=id;o.textContent=name;$("store").append(o);});$("store").value=selected;calendar();await showDay();$("status").textContent=index.unavailable_store_ids.length?`部分统计服务不可用：${index.unavailable_store_ids.length} 家，未补零。`:`已读取 ${Object.keys(index.store_names).length} 家门店的已保存副本。`;}catch(_){showError();}finally{busy=false;$("refresh").disabled=false;}}
$("month").value=day.slice(0,7);$("month").onchange=calendar;$("store").onchange=()=>{calendar();showDay().catch(showError);};$("queue").onchange=graphs;$("refresh").onclick=refresh;window.addEventListener("resize",graphs);refresh();setInterval(refresh,30000);
